USE mydb;
CREATE TABLE IF NOT EXISTS EMPLOYEDETAILS(id INT NOT NULL,Name VARCHAR(50) NOT NULL,dep VARCHAR(50) NOT NULL,PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS EMPLOYEE(empid INT NOT NULL,fname VARCHAR(30) NOT NULL,lname VARCHAR(30) NOT NULL,age INT NOT NULL,dep VARCHAR(50) NOT NULL,salary NUMERIC NOT NULL,FOREIGN KEY(empid) REFERENCES parent(id));
INSERT INTO EMPLOYEDETAILS VALUES(1,'John mathew','HR'),(2,'Iqbal Ahammed k','Sales'),(3,'Erwin James','IT'),(4,'Ramchand R','Adminstration');
INSERT INTO EMPLOYEE VALUES(1,'John','Mathew',32,'HR',30000),(2,'Iqbal Ahammed','K',27,'Sales',35000),(3,'Erwin','James',45,'IT',50000),(4,'Ramchand','R',27,'Adminstration',60000);
SELECT * FROM EMPLOYEE WHERE empid IN EMPLOYEDETAILS;
SELECT * FROM EMPLLOYEE WHERE empid NOT IN EMPLOYEDETAILS;
